/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ZegasScheduler } from "./ZegasScheduler";
export type { ZegasSmartTransfer } from "./ZegasSmartTransfer";
export type { ZegasTokenTransfer } from "./ZegasTokenTransfer";
